### PR TITLE
Add a Bitmask-Duration GA

### PR DESCRIPTION
**Pull request by zachdj**
This adds a GA that uses the bitmask-duration representation.

Full summary:
- Fitness function:
    - `distance`, if time is less than 75
    - `distance - time`, if time is greater than 75 or distance > 100

- Representation: Bitmask-duration
- Selection: Tournament of size 5
- Crossover:
    - 50% of the time: 2-point crossover
    - 50% of the time: cut-and-splice crossover
- Mutation: 
    - 50% of the time: apply Gaussian perturbation to a randomly selected duration with mean 0 and std deviation 7
    - 50% of the time: apply bit flip to one of the bitmasks, selected at random
- Replacement: replace one of the five worst members of the population, selected at random

### CODE REVIEW

**Comment by zachdj** [comment]
I ran this for 2500 evaluations and it didn't do very well.  I suspect the duration for each keystroke starts out (and remains) too low.  I may try running it again in the future.

**Comment by Mohamad9922** [comment]
> I ran this for 2500 evaluations and it did not do very well. I suspect the duration for each keystroke starts out (and remains) too low. I may try running it again in the future.
> 
> I also think the fitness function is pretty bad. Ideally, individuals would start out by learning a stable way to walk, then start trying to go faster

Great Job Zach, 
Yes we could try to improve it in the future. We could use some other representations and then go back to this one

**Comment by zachdj** [comment]
@Mohamad9922 If everything looks okay with this, could you approve the PR?

**Comment by Mohamad9922** [comment]
> @Mohamad9922 If everything looks okay with this, could you approve the PR?

Yes Sure

**Pull request merged**
